import mongoose, {Schema} from "mongoose";

export interface Action{
    _id?: mongoose.Types.ObjectId;
    user: mongoose.Types.ObjectId; // Reference to the user who performed the action
    description: string; // Description of the action (e.g., "Used a reusable coffee cup")
    sdgs: number[]; // Array of SDG numbers this action contributes to
    points: number; // Points earned for this action
    completedAt: Date; // Timestamp when the action was completed
    descriptionEmbedding?: number[]; // Vector embedding for the description (for vector search)
    category?: string; // Optional category for better grouping
    createdAt?: Date; // Auto-generated by timestamps
    updatedAt?: Date; // Auto-generated by timestamps
};

const ActionSchema: Schema<Action> = new mongoose.Schema<Action>({
    user: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    description: {
        type: String,
        required: true,
        trim: true
    },
    sdgs: {
        type: [Number],
        required: true,
        validate: {
            validator: function(sdgs: number[]) {
                return sdgs.length > 0 && sdgs.every(sdg => sdg >= 1 && sdg <= 17);
            },
            message: 'SDGs must be an array of numbers between 1 and 17'
        }
    },
    points: {
        type: Number,
        required: true,
        default: 10, // Default points per action
        min: 0
    },
    completedAt: {
        type: Date,
        required: true,
        default: Date.now
    },
    descriptionEmbedding: {
        type: [Number],
        // Vector embedding for the description - indexed by MongoDB Vector Search
    },
    category: {
        type: String,
        default: 'general'
    }
}, {
    timestamps: true
});

// Index for efficient queries
ActionSchema.index({ user: 1, completedAt: -1 });
ActionSchema.index({ sdgs: 1 });

export const ActionModel = mongoose.models.Action as mongoose.Model<Action> || 
mongoose.model<Action>('Action', ActionSchema);



